name: vr180cameraapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  device_info_plus: ^9.1.2
  flutter:
    sdk: flutter
  flutter_nearby_connections: ^1.1.2
  gallery_saver: ^2.3.2
  rename_app: ^1.3.2
  video_player: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
